spring:
  application:
    name: mesh-control-platform-api

sk:
  openApi:
    poi:
      appKey: 10b3e011-6d49-3ea5-bab3-f5e264bd78fd
      url: https://apis.skplanetx.com/tmap/pois
      version: 1
      resCoordType: WGS84GEO
      searchType: all
      searchtypCd: A
      count: 99

azure:
  ad:
    accessTokenUri: https://login.microsoftonline.com/meshkorea.net/oauth2/v2.0/token
    stsDiscoveryEndpoint: https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration
    scope: https://graph.microsoft.com/.default
    grantType: client_credentials
    clientId: 2da95571-ed3f-4851-b784-e02f37fe5978
    clientSecret: DZTnyOxoOJ5rFT0jwprZeOQ
    graph:
      api:
        users:
          url: https://graph.microsoft.com/v1.0/users
          top: 1000

google:
  openidConnect:
    jwksUri: https://www.googleapis.com/oauth2/v3/certs
    resourceId: 791029310581-lbcc802mm1n87ektvo98klr0gbp7eun5.apps.googleusercontent.com

mms:
  callbackNum: '18008255'
