spring:
  application:
    name: mesh-control-platform-api

sk:
  openApi:
    poi:
      appKey: a1a329d4-9f90-33c9-a257-6ba6487575b9
      url: https://apis.skplanetx.com/tmap/pois
      version: 1
      resCoordType: WGS84GEO
      searchType: all
      searchtypCd: A
      count: 99
