spring:
  application:
    name: mesh-control-platform-api

sk:
  openApi:
    poi:
      appKey: 10b3e011-6d49-3ea5-bab3-f5e264bd78fd
      url: https://apis.skplanetx.com/tmap/pois
      version: 1
      resCoordType: WGS84GEO
      searchType: all
      searchtypCd: A
      count: 99
