-- MySQL Script generated by MySQL Workbench
-- Tue Jul  4 16:54:52 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mcp
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema auth
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mms` DEFAULT CHARACTER SET utf8 ;
USE `mms` ;

-- -----------------------------------------------------
-- Table `mms`.`mms_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`mms_summary` (
  `mms_summary_no` INT NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `mms_sender` VARCHAR(20) NOT NULL COMMENT '발송자',
  `mms_trans_date` DATETIME NOT NULL COMMENT '발송일시',
  PRIMARY KEY (`mms_summary_no`),
  INDEX `idx_mms_sender` (`mms_sender` ASC),
  INDEX `idx_mms_trans_date` (`mms_trans_date` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mms`.`kb_mms_grp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`kb_mms_grp` (
  `TRAN_GRP_KEY` VARCHAR(16) NOT NULL COMMENT 'PK',
  `TRAN_REFKEY` VARCHAR(20) NULL DEFAULT NULL COMMENT '업체측에서 사용하는 필드',
  `TRAN_ID` VARCHAR(20) NULL DEFAULT NULL COMMENT '업체측에서 사용하는 필드',
  `TRAN_CALLBACK` VARCHAR(15) NOT NULL COMMENT '회신번호 ( G/W 전달값 )',
  `TRAN_SUBJECT` VARCHAR(100) NULL DEFAULT NULL COMMENT 'MMS 전송 제목 ( G/W 전달값 )',
  `TRAN_MSG` TEXT NOT NULL COMMENT '전송 메세지  ( G/W 전달값 )',
  `TRAN_DATE` DATETIME NOT NULL COMMENT '전송요청시간',
  `TRAN_TYPE` INT(11) NOT NULL COMMENT '4 : MMS',
  `TRAN_STATUS` CHAR(1) NOT NULL DEFAULT '1' COMMENT '1:전송 (메시지 초기 입력 상태 )\n4:전송중\n2:KSKYB 전송완료',
  `TRAN_SENDDATE` DATETIME NULL DEFAULT NULL COMMENT '전송시작일자',
  `TRAN_RECEIVER_CNT` INT(11) NOT NULL COMMENT '기본 : 1 동보일 경우 전체전송숫자',
  `TRAN_ETC1` VARCHAR(160) NULL DEFAULT NULL COMMENT '업체측에서 사용하는 필드',
  `TRAN_ETC2` VARCHAR(160) NULL DEFAULT NULL COMMENT '업체측에서 사용하는 필드',
  `TRAN_ETC3` VARCHAR(160) NULL DEFAULT NULL COMMENT '업체측에서 사용하는 필드',
  `TRAN_ETC4` VARCHAR(160) NULL DEFAULT NULL COMMENT '업체측에서 사용하는 필드',
  `TRAN_ETC5` VARCHAR(160) NULL DEFAULT NULL COMMENT '업체측에서 사용하는 필드',
  `TRAN_LOG` CHAR(1) NULL DEFAULT 'N' COMMENT 'default ‘N’  테이블백업관련 Agent사용값',
  `mms_summary_no` INT NOT NULL COMMENT 'mms_summary FK',
  PRIMARY KEY (`TRAN_GRP_KEY`),
  INDEX `idx1_kb_mms_grp` (`TRAN_DATE` ASC),
  INDEX `idx2_kb_mms_grp` (`TRAN_STATUS` ASC),
  INDEX `fk_kb_mms_grp_mms_summary1_idx` (`mms_summary_no` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mms`.`kb_mms_contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`kb_mms_contents` (
  `TRAN_GRP_KEY` VARCHAR(16) NOT NULL COMMENT 'kb_mms_grp FK',
  `CONTENT_SEQ` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `CONTENT_TYPE` VARCHAR(3) NOT NULL COMMENT '컨텐츠 유형 (TXT,IMG,SND,VDO )',
  `CONTENT_NAME` VARCHAR(255) NOT NULL COMMENT '전송파일이름\nAgent 설정디렉토리 이하의 파일Path 입력\n전송파일은 MMS Agent 가 구동되는 시스템에 존재해야 한다.',
  `CONTENT_SVC` VARCHAR(3) NULL DEFAULT NULL COMMENT 'default ‘ALL’\n‘SKT’,’KTF’,’LGT’,’ALL’',
  `TRAN_LOG` CHAR(1) NULL DEFAULT 'N' COMMENT 'default ‘N’  테이블백업관련 Agent사용값',
  PRIMARY KEY (`CONTENT_SEQ`),
  INDEX `fk_kb_mms_contents_kb_mms_grp1_idx` (`TRAN_GRP_KEY` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mms`.`kb_mms_grp_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`kb_mms_grp_log` (
  `TRAN_GRP_KEY` VARCHAR(16) NOT NULL COMMENT 'PK',
  `TRAN_REFKEY` VARCHAR(20) NULL DEFAULT NULL COMMENT '업체측에서 사용하는 필드',
  `TRAN_ID` VARCHAR(20) NULL DEFAULT NULL COMMENT '업체측에서 사용하는 필드',
  `TRAN_CALLBACK` VARCHAR(15) NOT NULL COMMENT '회신번호 ( G/W 전달값 )',
  `TRAN_SUBJECT` VARCHAR(100) NULL DEFAULT NULL COMMENT 'MMS 전송 제목 ( G/W 전달값 )',
  `TRAN_MSG` TEXT NOT NULL COMMENT '전송 메세지  ( G/W 전달값 )',
  `TRAN_DATE` DATETIME NOT NULL COMMENT '전송요청시간',
  `TRAN_TYPE` INT(11) NOT NULL COMMENT '4 : MMS',
  `TRAN_STATUS` CHAR(1) NOT NULL DEFAULT '1' COMMENT '1:전송 (메시지 초기 입력 상태 )\n4:전송중\n2:KSKYB 전송완료',
  `TRAN_SENDDATE` DATETIME NULL DEFAULT NULL COMMENT '전송시작일자',
  `TRAN_RECEIVER_CNT` INT(11) NOT NULL COMMENT '기본 : 1 동보일 경우 전체전송숫자',
  `TRAN_ETC1` VARCHAR(160) NULL DEFAULT NULL COMMENT '업체측에서 사용하는 필드',
  `TRAN_ETC2` VARCHAR(160) NULL DEFAULT NULL COMMENT '업체측에서 사용하는 필드',
  `TRAN_ETC3` VARCHAR(160) NULL DEFAULT NULL COMMENT '업체측에서 사용하는 필드',
  `TRAN_ETC4` VARCHAR(160) NULL DEFAULT NULL COMMENT '업체측에서 사용하는 필드',
  `TRAN_ETC5` VARCHAR(160) NULL DEFAULT NULL COMMENT '업체측에서 사용하는 필드',
  `TRAN_LOG` CHAR(1) NULL DEFAULT 'N' COMMENT 'default ‘N’  테이블백업관련 Agent사용값',
  `mms_summary_no` INT NOT NULL COMMENT 'mms_summary FK',
  INDEX `idx1_kb_mms_grp_log` (`TRAN_GRP_KEY` ASC),
  INDEX `idx2_kb_mms_grp_log` (`TRAN_DATE` ASC),
  PRIMARY KEY (`TRAN_GRP_KEY`),
  INDEX `fk_kb_mms_grp_log_mms_summary1_idx` (`mms_summary_no` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mms`.`kb_mms_contents_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`kb_mms_contents_log` (
  `TRAN_GRP_KEY` VARCHAR(16) NOT NULL COMMENT 'kb_mms_grp_log FK',
  `CONTENT_SEQ` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `CONTENT_TYPE` VARCHAR(3) NOT NULL COMMENT '컨텐츠 유형 (TXT,IMG,SND,VDO )',
  `CONTENT_NAME` VARCHAR(255) NOT NULL COMMENT '전송파일이름\nAgent 설정디렉토리 이하의 파일Path 입력\n전송파일은 MMS Agent 가 구동되는 시스템에 존재해야 한다.',
  `CONTENT_SVC` VARCHAR(3) NULL DEFAULT NULL COMMENT 'default ‘ALL’\n‘SKT’,’KTF’,’LGT’,’ALL’',
  `TRAN_LOG` CHAR(1) NULL DEFAULT 'N' COMMENT 'default ‘N’  테이블백업관련 Agent사용값',
  PRIMARY KEY (`CONTENT_SEQ`),
  INDEX `fk_kb_mms_contents_log_kb_mms_grp_log1_idx` (`TRAN_GRP_KEY` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mms`.`kb_mms_tran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`kb_mms_tran` (
  `TRAN_GRP_KEY` VARCHAR(16) NOT NULL COMMENT 'kb_mms_grp FK',
  `TRAN_MSG_KEY` VARCHAR(16) NOT NULL COMMENT 'PK',
  `TRAN_PHONE` VARCHAR(15) NOT NULL COMMENT '수신번호',
  `TRAN_EXTEND` VARCHAR(86) NULL DEFAULT NULL COMMENT '부가데이터 ( G/W로 전송 )',
  `TRAN_STATUS` CHAR(1) NOT NULL DEFAULT '1' COMMENT '1:전송 (메시지 초기 입력 상태 )\n4:전송중\n2:KSKYB 전송완료\n3:전송결과수신',
  `TRAN_DATE` DATETIME NULL DEFAULT NULL COMMENT '전송요청시간',
  `TRAN_SENDDATE` DATETIME NULL DEFAULT NULL COMMENT 'GW전송시간',
  `TRAN_REPORTDATE` DATETIME NULL DEFAULT NULL COMMENT '전송결과수신시간',
  `TRAN_RSLTDATE` DATETIME NULL DEFAULT NULL COMMENT '휴대폰 수신시간(이통사전송값)',
  `TRAN_RSLT` VARCHAR(5) NULL DEFAULT NULL COMMENT '전송결과코드',
  `TRAN_END_TELCO` VARCHAR(5) NULL DEFAULT NULL COMMENT '착신망 정보',
  `TRAN_LOG` CHAR(1) NULL DEFAULT 'N' COMMENT 'default ‘N’  테이블백업관련 Agent사용값',
  `TRAN_RECEIVER` VARCHAR(20) NULL DEFAULT NULL COMMENT '수신자',
  PRIMARY KEY (`TRAN_MSG_KEY`),
  INDEX `idx1_kb_mms_tran` (`TRAN_STATUS` ASC),
  INDEX `fk_kb_mms_tran_kb_mms_grp_idx` (`TRAN_GRP_KEY` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mms`.`kb_mms_tran_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`kb_mms_tran_log` (
  `TRAN_GRP_KEY` VARCHAR(16) NOT NULL COMMENT 'kb_mms_grp_log FK',
  `TRAN_MSG_KEY` VARCHAR(16) NOT NULL COMMENT 'PK',
  `TRAN_PHONE` VARCHAR(15) NOT NULL COMMENT '수신번호',
  `TRAN_EXTEND` VARCHAR(86) NULL DEFAULT NULL COMMENT '부가데이터 ( G/W로 전송 )',
  `TRAN_STATUS` CHAR(1) NOT NULL DEFAULT '1' COMMENT '1:전송 (메시지 초기 입력 상태 )\n4:전송중\n2:KSKYB 전송완료\n3:전송결과수신',
  `TRAN_DATE` DATETIME NULL DEFAULT NULL COMMENT '전송요청시간',
  `TRAN_SENDDATE` DATETIME NULL DEFAULT NULL COMMENT 'GW전송시간',
  `TRAN_REPORTDATE` DATETIME NULL DEFAULT NULL COMMENT '전송결과수신시간',
  `TRAN_RSLTDATE` DATETIME NULL DEFAULT NULL COMMENT '휴대폰 수신시간(이통사전송값)',
  `TRAN_RSLT` VARCHAR(5) NULL DEFAULT NULL COMMENT '전송결과코드',
  `TRAN_END_TELCO` VARCHAR(5) NULL DEFAULT NULL COMMENT '착신망 정보',
  `TRAN_LOG` CHAR(1) NULL DEFAULT 'N' COMMENT 'default ‘N’  테이블백업관련 Agent사용값',
  `TRAN_RECEIVER` VARCHAR(20) NULL DEFAULT NULL COMMENT '수신자',
  INDEX `idx2_kb_mms_tran_log` (`TRAN_STATUS` ASC),
  INDEX `idx3_kb_mms_tran_log` (`TRAN_DATE` ASC),
  PRIMARY KEY (`TRAN_MSG_KEY`),
  INDEX `fk_kb_mms_tran_log_kb_mms_grp_log1_idx` (`TRAN_GRP_KEY` ASC),
  INDEX `idx_tran_phone` (`TRAN_PHONE` ASC),
  INDEX `idx_tran_receiver` (`TRAN_RECEIVER` ASC)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mms`.`kb_tran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`kb_tran` (
  `TRAN_PR` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `TRAN_REFKEY` VARCHAR(20) NULL DEFAULT NULL,
  `TRAN_ID` VARCHAR(20) NULL DEFAULT NULL,
  `TRAN_PHONE` VARCHAR(15) NOT NULL,
  `TRAN_CALLBACK` VARCHAR(15) NOT NULL,
  `TRAN_MSG` VARCHAR(150) NOT NULL,
  `TRAN_DATE` DATETIME NOT NULL,
  `TRAN_TYPE` INT(11) NOT NULL DEFAULT '0',
  `TRAN_STATUS` CHAR(1) NOT NULL DEFAULT '1',
  `TRAN_SENDDATE` DATETIME NULL DEFAULT NULL,
  `TRAN_REPORTDATE` DATETIME NULL DEFAULT NULL,
  `TRAN_RSLTDATE` DATETIME NULL DEFAULT NULL,
  `TRAN_RSLT` CHAR(2) NULL DEFAULT NULL,
  `TRAN_ETC1` VARCHAR(160) NULL DEFAULT NULL,
  `TRAN_ETC2` VARCHAR(160) NULL DEFAULT NULL,
  `TRAN_ETC3` VARCHAR(160) NULL DEFAULT NULL,
  `TRAN_ETC4` VARCHAR(160) NULL DEFAULT NULL,
  `TRAN_ETC5` VARCHAR(160) NULL DEFAULT NULL,
  `TRAN_END_TELCO` VARCHAR(8) NULL DEFAULT NULL,
  `TRAN_LOG` CHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`TRAN_PR`),
  INDEX `kb_tran_IDX1` (`TRAN_STATUS` ASC),
  INDEX `kb_tran_IDX2` (`TRAN_DATE` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mms`.`kb_tran_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`kb_tran_log` (
  `TRAN_PR` BIGINT(20) NOT NULL,
  `TRAN_REFKEY` VARCHAR(20) NULL DEFAULT NULL,
  `TRAN_ID` VARCHAR(20) NULL DEFAULT NULL,
  `TRAN_PHONE` VARCHAR(15) NOT NULL,
  `TRAN_CALLBACK` VARCHAR(15) NOT NULL,
  `TRAN_MSG` VARCHAR(150) NOT NULL,
  `TRAN_DATE` DATETIME NOT NULL,
  `TRAN_TYPE` INT(11) NOT NULL DEFAULT '0',
  `TRAN_STATUS` CHAR(1) NOT NULL DEFAULT '1',
  `TRAN_SENDDATE` DATETIME NULL DEFAULT NULL,
  `TRAN_REPORTDATE` DATETIME NULL DEFAULT NULL,
  `TRAN_RSLTDATE` DATETIME NULL DEFAULT NULL,
  `TRAN_RSLT` CHAR(2) NULL DEFAULT NULL,
  `TRAN_ETC1` VARCHAR(160) NULL DEFAULT NULL,
  `TRAN_ETC2` VARCHAR(160) NULL DEFAULT NULL,
  `TRAN_ETC3` VARCHAR(160) NULL DEFAULT NULL,
  `TRAN_ETC4` VARCHAR(160) NULL DEFAULT NULL,
  `TRAN_ETC5` VARCHAR(160) NULL DEFAULT NULL,
  `TRAN_END_TELCO` VARCHAR(8) NULL DEFAULT NULL,
  `TRAN_LOG` CHAR(1) NULL DEFAULT 'N',
  INDEX `kb_tran_log_IDX1` (`TRAN_PR` ASC),
  INDEX `kb_tran_log_IDX2` (`TRAN_STATUS` ASC),
  INDEX `kb_tran_log_IDX3` (`TRAN_DATE` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
