-- MySQL Script generated by MySQL Workbench
-- Tue Jun 13 23:13:02 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mcp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mcp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mcp` DEFAULT CHARACTER SET utf8 ;
USE `mcp` ;

-- -----------------------------------------------------
-- Table `mcp`.`claim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcp`.`claim` (
  `claim_no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `status_code` VARCHAR(20) NOT NULL COMMENT '처리 상태',
  `type_code` VARCHAR(20) NOT NULL COMMENT '클레임 유형',
  `request_code` VARCHAR(20) NOT NULL COMMENT '요청 주체',
  `cause_code` VARCHAR(20) NOT NULL COMMENT '클레임 사유',
  `customer_blame` FLOAT NULL COMMENT '고객 귀책 ratio',
  `store_blame` FLOAT NULL COMMENT '상점 귀책 ratio',
  `partner_blame` FLOAT NULL COMMENT '파트너 귀책 ratio',
  `mesh_blame` FLOAT NULL COMMENT '메쉬코리아 귀책 ratio',
  `none_blame` FLOAT NULL COMMENT '귀책 없음 ratio',
  `creator` VARCHAR(50) NOT NULL COMMENT '생성자',
  `create_dt` DATETIME NOT NULL COMMENT '생성일시',
  `updater` VARCHAR(50) NULL COMMENT '수정자',
  `update_dt` DATETIME NULL COMMENT '수정일시',
  PRIMARY KEY (`claim_no`),
  INDEX `idx_create_dt_status` (`create_dt` ASC, `status_code` ASC),
  INDEX `idx_create_dt_type` (`create_dt` ASC, `type_code` ASC))
ENGINE = InnoDB
COMMENT = '클레임 테이블';


-- -----------------------------------------------------
-- Table `mcp`.`claim_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcp`.`claim_history` (
  `claim_history_no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `claim_no` BIGINT NOT NULL COMMENT 'FK',
  `creator` VARCHAR(50) NOT NULL COMMENT '생성자',
  `create_dt` DATETIME NOT NULL COMMENT '생성일시',
  `json_string` TEXT NULL COMMENT 'claim 테이블 전체 데이터 - json',
  PRIMARY KEY (`claim_history_no`),
  INDEX `fk_claim_no` (`claim_no` ASC),
  CONSTRAINT `fk_claim_history_claim1`
    FOREIGN KEY (`claim_no`)
    REFERENCES `mcp`.`claim` (`claim_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '클레임 이력 테이블';


-- -----------------------------------------------------
-- Table `mcp`.`codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcp`.`codes` (
  `code_no` INT NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `parent_code_no` INT NOT NULL COMMENT 'FK',
  `code` VARCHAR(20) NOT NULL COMMENT '읽기 가능한 문자로 된 코드',
  `code_name` VARCHAR(100) NOT NULL COMMENT '코드명',
  `display_order` INT NOT NULL COMMENT '같은 부모를 가지는 코드일 경우 정렬 순서',
  `description` VARCHAR(200) NULL COMMENT '코드에 대한 설명',
  `creator` VARCHAR(50) NOT NULL COMMENT '생성자',
  `create_dt` DATETIME NOT NULL COMMENT '생성일시',
  `updater` VARCHAR(50) NULL COMMENT '수정자',
  `update_dt` DATETIME NULL COMMENT '수정일시',
  PRIMARY KEY (`code_no`),
  UNIQUE INDEX `idx_code_parent` (`code` ASC, `parent_code_no` ASC),
  INDEX `fk_parent_code_no` (`parent_code_no` ASC),
  UNIQUE INDEX `idx_parent_code` (`parent_code_no` ASC, `code` ASC),
  CONSTRAINT `fk_codes_codes1`
    FOREIGN KEY (`parent_code_no`)
    REFERENCES `mcp`.`codes` (`code_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '코드성 데이터를 관리하는 테이블 - 코드간 hierarchy 를 표현 할 수 있음';


-- -----------------------------------------------------
-- Table `mcp`.`order_claim_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcp`.`order_claim_relation` (
  `order_id` BIGINT(20) NOT NULL COMMENT 'PK',
  `claim_no` BIGINT NOT NULL COMMENT 'PK',
  `claim_order_id` BIGINT(20) NULL COMMENT 'FK',
  `orderNumber` VARCHAR(255) NULL,
  `claimOrderNumber` VARCHAR(255) NULL,
  PRIMARY KEY (`order_id`, `claim_no`),
  INDEX `fk_order_claim_relation_order` (`order_id` ASC),
  INDEX `fk_order_claim_relation_claim` (`claim_no` ASC),
  INDEX `fk_order_claim_relation_claim_order` (`claim_order_id` ASC),
  INDEX `idx_claim_relation_order` (`claim_no` ASC, `claim_order_id` ASC),
  CONSTRAINT `fk_order_claim_relation_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mcp`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_claim_relation_claim1`
    FOREIGN KEY (`claim_no`)
    REFERENCES `mcp`.`claim` (`claim_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_claim_relation_orders2`
    FOREIGN KEY (`claim_order_id`)
    REFERENCES `mcp`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'orders 테이블과 claim 테이블의 연관관계 매핑을 위한 테이블';


-- -----------------------------------------------------
-- Table `mcp`.`claim_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcp`.`claim_description` (
  `claim_description_no` INT NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `order_id` BIGINT(20) NOT NULL COMMENT 'FK',
  `claim_no` BIGINT NOT NULL COMMENT 'FK',
  `description` VARCHAR(255) NOT NULL COMMENT '비고 - 정산 참고용 description',
  `creator` VARCHAR(50) NOT NULL COMMENT '생성자',
  `create_dt` DATETIME NOT NULL COMMENT '생성일시',
  PRIMARY KEY (`claim_description_no`),
  INDEX `fk_order_relation_claim` (`order_id` ASC, `claim_no` ASC),
  CONSTRAINT `fk_claim_description_order_claim_relation1`
    FOREIGN KEY (`order_id` , `claim_no`)
    REFERENCES `mcp`.`order_claim_relation` (`order_id` , `claim_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '클레임 비고사항 기록을 위한 테이블';


-- -----------------------------------------------------
-- Table `mcp`.`claim_adjustment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcp`.`claim_adjustment` (
  `claim_adjustment_no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `order_id` BIGINT(20) NOT NULL COMMENT 'FK',
  `claim_no` BIGINT NOT NULL COMMENT 'FK',
  `adjustment_value` INT NULL COMMENT '정산 - 타입에 따라 퍼센트와 금액이 들어갈 수 있다',
  `adjustment_type_code` VARCHAR(20) NULL COMMENT '정산 비율/타입 구분 코드',
  `delivery_fee_value` INT NULL COMMENT '배송 - 타입에 따라 퍼센트와 금액이 들어갈 수 있다',
  `delivery_fee_type_code` VARCHAR(20) NULL COMMENT '배송 비율/금액 구분 코드',
  `cancel_fee_value` INT NULL COMMENT '취소 수수료 - 타입에 따라 퍼센트와 금액이 들어갈 수 있다',
  `cancel_fee_type_code` VARCHAR(20) NULL COMMENT '취소 수수료 비율/금액 구분 코드',
  `creator` VARCHAR(50) NOT NULL COMMENT '생성자',
  `create_dt` DATETIME NOT NULL COMMENT '생성일시',
  `updater` VARCHAR(50) NULL COMMENT '수정자',
  `update_dt` DATETIME NULL COMMENT '수정일시',
  PRIMARY KEY (`claim_adjustment_no`),
  INDEX `fk_order_relation_claim` (`order_id` ASC, `claim_no` ASC),
  CONSTRAINT `fk_claim_adjustment_order_claim_relation1`
    FOREIGN KEY (`order_id` , `claim_no`)
    REFERENCES `mcp`.`order_claim_relation` (`order_id` , `claim_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '클레임에 의한 정산금 분배를 위한 금액 데이터 테이블';


-- -----------------------------------------------------
-- Table `mcp`.`claim_adjustment_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcp`.`claim_adjustment_history` (
  `claim_adjustment_history_no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `claim_adjustment_no` BIGINT NOT NULL COMMENT 'FK',
  `creator` VARCHAR(50) NOT NULL COMMENT '생성자',
  `create_dt` DATETIME NOT NULL COMMENT '생성일시',
  `json_string` TEXT NULL COMMENT '클레임 정산 금액 테이블 전체 데이터 - json',
  PRIMARY KEY (`claim_adjustment_history_no`),
  INDEX `fk_claim_adjustment_no` (`claim_adjustment_no` ASC),
  CONSTRAINT `fk_claim_adjustment_history_claim_adjustment1`
    FOREIGN KEY (`claim_adjustment_no`)
    REFERENCES `mcp`.`claim_adjustment` (`claim_adjustment_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '클레임 정산금 분배 관련 변경 이력';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;