-- MySQL Script generated by MySQL Workbench
-- Tue Jun 13 23:13:02 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mcp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mcp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mcp` DEFAULT CHARACTER SET utf8 ;
USE `mcp` ;

-- -----------------------------------------------------
-- Table `mcp`.`claim`
-- -----------------------------------------------------
CREATE TABLE `claim` (
  `claim_no` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `status_code` varchar(20) NOT NULL COMMENT '처리 상태',
  `type_code` varchar(20) NOT NULL COMMENT '클레임 유형',
  `request_code` varchar(20) NOT NULL COMMENT '요청 주체',
  `cause_code` varchar(20) NOT NULL COMMENT '클레임 사유',
  `customer_blame` float DEFAULT NULL COMMENT '고객 귀책 ratio',
  `store_blame` float DEFAULT NULL COMMENT '상점 귀책 ratio',
  `partner_blame` float DEFAULT NULL COMMENT '파트너 귀책 ratio',
  `mesh_blame` float DEFAULT NULL COMMENT '메쉬코리아 귀책 ratio',
  `none_blame` float DEFAULT NULL COMMENT '귀책 없음 ratio',
  `creator` varchar(50) NOT NULL COMMENT '생성자',
  `create_dt` datetime NOT NULL COMMENT '생성일시',
  `updater` varchar(50) DEFAULT NULL COMMENT '수정자',
  `update_dt` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`claim_no`),
  KEY `idx_create_dt_status` (`create_dt`,`status_code`),
  KEY `idx_create_dt_type` (`create_dt`,`type_code`)
) ENGINE=InnoDB AUTO_INCREMENT=200000000001 DEFAULT CHARSET=utf8 COMMENT='클레임 테이블';


-- -----------------------------------------------------
-- Table `mcp`.`claim_history`
-- -----------------------------------------------------
CREATE TABLE `claim_history` (
  `claim_history_no` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `claim_no` bigint(20) NOT NULL COMMENT 'FK',
  `creator` varchar(50) NOT NULL COMMENT '생성자',
  `create_dt` datetime NOT NULL COMMENT '생성일시',
  `json_string` text COMMENT 'claim 테이블 전체 데이터 - json',
  PRIMARY KEY (`claim_history_no`),
  KEY `fk_claim_no` (`claim_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='클레임 이력 테이블';


-- -----------------------------------------------------
-- Table `mcp`.`codes`
-- -----------------------------------------------------
CREATE TABLE `mcp`.`codes` (
  `code_no` int(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `parent_code_no` int(11) DEFAULT NULL COMMENT 'FK',
  `code` varchar(20) NOT NULL COMMENT '읽기 가능한 문자로 된 코드',
  `code_name` varchar(100) NOT NULL COMMENT '코드명',
  `display_order` int(11) NOT NULL COMMENT '같은 부모를 가지는 코드일 경우 정렬 순서',
  `description` varchar(200) DEFAULT NULL COMMENT '코드에 대한 설명',
  `creator` varchar(50) NOT NULL COMMENT '생성자',
  `create_dt` datetime NOT NULL COMMENT '생성일시',
  `updater` varchar(50) DEFAULT NULL COMMENT '수정자',
  `update_dt` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`code_no`),
  KEY `idx_code_parent` (`code`,`parent_code_no`),
  KEY `fk_parent_code_no` (`parent_code_no`),
  KEY `idx_code` (`code`),
  KEY `idx_parent_display_order` (`parent_code_no`,`display_order`)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8
COMMENT='코드성 데이터를 관리하는 테이블 - 코드간 hierarchy 를 표현 할 수 있음';


-- -----------------------------------------------------
-- Table `mcp`.`order_claim_relation`
-- -----------------------------------------------------
CREATE TABLE `order_claim_relation` (
  `order_id` bigint(20) NOT NULL COMMENT 'PK',
  `claim_no` bigint(20) NOT NULL COMMENT 'PK',
  `claim_order_id` bigint(20) DEFAULT NULL COMMENT 'FK',
  `order_number` varchar(255) DEFAULT NULL,
  `claim_order_number` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`order_id`,`claim_no`),
  KEY `fk_order_claim_relation_order` (`order_id`),
  KEY `fk_order_claim_relation_claim` (`claim_no`),
  KEY `fk_order_claim_relation_claim_order` (`claim_order_id`),
  KEY `idx_claim_relation_order` (`claim_no`,`claim_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='orders 테이블과 claim 테이블의 연관관계 매핑을 위한 테이블';


-- -----------------------------------------------------
-- Table `mcp`.`claim_description`
-- -----------------------------------------------------
CREATE TABLE `claim_description` (
  `claim_description_no` int(11) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `order_id` bigint(20) NOT NULL COMMENT 'FK',
  `claim_no` bigint(20) NOT NULL COMMENT 'FK',
  `description` varchar(255) NOT NULL COMMENT '비고 - 정산 참고용 description',
  `creator` varchar(50) NOT NULL COMMENT '생성자',
  `create_dt` datetime NOT NULL COMMENT '생성일시',
  PRIMARY KEY (`claim_description_no`),
  KEY `fk_order_relation_claim` (`order_id`,`claim_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='클레임 비고사항 기록을 위한 테이블';


-- -----------------------------------------------------
-- Table `mcp`.`claim_adjustment`
-- -----------------------------------------------------
CREATE TABLE `claim_adjustment` (
  `claim_adjustment_no` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `order_id` bigint(20) NOT NULL COMMENT 'FK',
  `claim_no` bigint(20) NOT NULL COMMENT 'FK',
  `adjustment_value` int(11) DEFAULT NULL COMMENT '정산 - 타입에 따라 퍼센트와 금액이 들어갈 수 있다',
  `adjustment_type_code` varchar(20) DEFAULT NULL COMMENT '정산 비율/타입 구분 코드',
  `delivery_fee_value` int(11) DEFAULT NULL COMMENT '배송 - 타입에 따라 퍼센트와 금액이 들어갈 수 있다',
  `delivery_fee_type_code` varchar(20) DEFAULT NULL COMMENT '배송 비율/금액 구분 코드',
  `cancel_fee_value` int(11) DEFAULT NULL COMMENT '취소 수수료 - 타입에 따라 퍼센트와 금액이 들어갈 수 있다',
  `cancel_fee_type_code` varchar(20) DEFAULT NULL COMMENT '취소 수수료 비율/금액 구분 코드',
  `creator` varchar(50) NOT NULL COMMENT '생성자',
  `create_dt` datetime NOT NULL COMMENT '생성일시',
  `updater` varchar(50) DEFAULT NULL COMMENT '수정자',
  `update_dt` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`claim_adjustment_no`),
  KEY `fk_order_relation_claim` (`order_id`,`claim_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='클레임에 의한 정산금 분배를 위한 금액 데이터 테이블';


-- -----------------------------------------------------
-- Table `mcp`.`claim_adjustment_history`
-- -----------------------------------------------------
CREATE TABLE `claim_adjustment_history` (
  `claim_adjustment_history_no` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `claim_adjustment_no` bigint(20) NOT NULL COMMENT 'FK',
  `creator` varchar(50) NOT NULL COMMENT '생성자',
  `create_dt` datetime NOT NULL COMMENT '생성일시',
  `json_string` text COMMENT '클레임 정산 금액 테이블 전체 데이터 - json',
  PRIMARY KEY (`claim_adjustment_history_no`),
  KEY `fk_claim_adjustment_no` (`claim_adjustment_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='클레임 정산금 분배 관련 변경 이력';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;