/*
-- Query: SELECT * FROM mcp.codes
LIMIT 0, 1000

-- Date: 2017-07-10 15:08
*/
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (1,NULL,'USER_TYPE','사용자 유형',1,'사용자 유형 코드 parent','yjhan','2017-06-15 18:59:59',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (2,1,'GENERAL','일반',1,'사용자 유형 코드 - 일반','yjhan','2017-06-15 18:59:59',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (7,NULL,'USER_SEARCH_TYPE','사용자 조회 타입',1,'사용자 조회 타입 parent','yjhan','2017-06-15 18:59:59',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (8,7,'USER_ID','통합 ID',1,'사용자 조회 타입 - 통합 ID','yjhan','2017-06-15 18:59:59',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (9,7,'USER_NAME','사용자 명',2,'사용자 조회 타입 - 사용자 명','yjhan','2017-06-15 18:59:59',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (10,NULL,'CLAIM_STATUS_TYPE','클레임 상태',1,'클레임 상태 코드 parent','sungjae.hong','2017-06-16 16:12:26',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (11,10,'ACCEPT','접수',1,'클레임 상태 코드 - 접수','sungjae.hong','2017-06-16 17:46:03',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (12,10,'IN_PROGRESS','처리중',2,'클레임 상태 코드 - 처리중','sungjae.hong','2017-06-16 17:46:03',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (13,10,'HOLD','보류',3,'클레임 상태 코드 - 보류','sungjae.hong','2017-06-16 17:46:03',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (14,10,'RESOLVE','해결',4,'클레임 상태 코드 - 해결','sungjae.hong','2017-06-16 17:46:03',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (15,10,'RETRACTION','철회',5,'클레임 상태 코드 - 철회','sungjae.hong','2017-06-16 17:46:03',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (16,10,'TRANSFER','이관',6,'클레임 상태 코드 - 이관','sungjae.hong','2017-06-16 17:46:03',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (17,10,'UNPROCESSED','미처리(처리불가)',7,'클레임 상태 코드 - 미처리(처리불가)','sungjae.hong','2017-06-16 17:46:03',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (18,NULL,'CLAIM_TYPE','클레임 유형',1,'클레임 유형 코드 parent','sungjae.hong','2017-06-16 18:00:12',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (19,18,'CANCELED','취소',1,'클레임 유형 코드 - 취소','sungjae.hong','2017-06-16 18:23:52',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (20,18,'REFUND','환불',2,'클레임 유형 코드 - 환불','sungjae.hong','2017-06-16 18:23:52',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (21,18,'RESEND','재배송',3,'클레임 유형 코드 - 재배송','sungjae.hong','2017-06-16 18:23:52',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (22,18,'EXCHANGE','교환',4,'클레임 유형 코드 - 교환','sungjae.hong','2017-06-16 18:23:52',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (23,18,'CHANGE_DEST','배송지변경',5,'클레임 유형 코드 - 배송지변경','sungjae.hong','2017-06-16 18:23:52',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (24,18,'CHANGE_PAY_METHOD','결제수단변경',6,'클레임 유형 코드 - 결제수단변경','sungjae.hong','2017-06-16 18:23:52',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (25,18,'CHANGE_AMOUNT','결제금액변경',7,'클레임 유형 코드 - 결제금액변경','sungjae.hong','2017-06-16 18:23:52',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (26,18,'ETC','기타',8,'클레임 유형 코드 - 기타','sungjae.hong','2017-06-16 18:23:52',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (27,NULL,'REQUEST_TYPE','요청 주체',1,'요청 주체 코드 parent','sungjae.hong','2017-06-18 17:06:01',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (28,27,'STORE','상점',1,'요청 주체 코드 - 상점','sungjae.hong','2017-06-18 17:17:19',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (29,27,'CLIENT','고객',2,'요청 주체 코드 - 고객','sungjae.hong','2017-06-18 17:17:19',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (30,27,'PARTNER','파트너',3,'요청 주체 코드 - 파트너','sungjae.hong','2017-06-18 17:17:19',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (31,27,'AGENT','배송기사',4,'요청 주체 코드 - 배송기사','sungjae.hong','2017-06-18 17:17:19',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (32,27,'MESHKOREA','메쉬코리아',5,'요청 주체 코드 - 메쉬코리아','sungjae.hong','2017-06-18 17:17:19',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (33,27,'THE_OTHERS','기타',6,'요청 주체 코드 - 기타','sungjae.hong','2017-06-18 17:17:19',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (34,NULL,'CAUSE_TYPE','클레임 사유',1,'클레임 사유 parent','sungjae.hong','2017-06-18 17:36:22',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (35,34,'DELIVERY','배송',1,'클레임 사유 대분류 - 배송','sungjae.hong','2017-06-18 17:45:51',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (36,34,'PAYMENT','결제',2,'클레임 사유 대분류 - 결제','sungjae.hong','2017-06-18 17:45:51',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (37,34,'PRODUCT','상품',3,'클레임 사유 대분류 - 상품','sungjae.hong','2017-06-18 17:45:51',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (38,34,'THE_OTHERS','기타',4,'클레임 사유 대분류 - 기타','sungjae.hong','2017-06-18 17:45:51',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (39,35,'ALLOCATION_DELAY','배차지연',1,'클레임 사유 중분류 - 배차지연','sungjae.hong','2017-06-18 18:47:50',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (40,35,'PICKUP_DELAY','픽업지연',2,'클레임 사유 중분류 - 픽업지연','sungjae.hong','2017-06-18 18:47:50',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (41,35,'DELIVERY_DELAY','배송지연',3,'클레임 사유 중분류 - 배송지연','sungjae.hong','2017-06-18 18:47:50',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (42,35,'CAN_NOT_DELIVERY','배송불가',4,'클레임 사유 중분류 - 배송불가','sungjae.hong','2017-06-18 18:47:50',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (43,35,'DELIVERY_CANCEL','배차취소',5,'클레임 사유 중분류 - 배차취소','sungjae.hong','2017-06-18 18:47:50',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (44,35,'WRONG_DELIVERY','오배송',6,'클레임 사유 중분류 - 오배송','sungjae.hong','2017-06-18 18:47:50',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (45,35,'OVERLOAD','과적',7,'클레임 사유 중분류 - 과적','sungjae.hong','2017-06-18 18:47:50',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (46,36,'CAN_NOT_PAYMENT','결제불가',1,'클레임 사유 중분류 - 결제불가','sungjae.hong','2017-06-18 18:51:52',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (47,36,'WRONG_PAYMENT','오결제',2,'클레임 사유 중분류 - 오결제','sungjae.hong','2017-06-18 18:51:52',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (50,NULL,'GROUP_SEARCH_TYPE','그룹 조회 타입',1,'그룹 조회 타입 parent','yjhan','2017-06-18 18:56:57',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (51,50,'GROUP_NAME','권한 그룹명',1,'그룹 조회 타입 - 권한 그룹명','yjhan','2017-06-18 18:56:57',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (52,50,'GROUP_CODE','권한 그룹 코드',2,'그룹 조회 타입 - 권한 그룹 코드','yjhan','2017-06-18 18:56:57',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (63,37,'DEFECTIVE_GOODS','상품불량',1,'클레임 사유 중분류 - 상품불량','sungjae.hong','2017-06-18 20:11:50',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (64,37,'OMITTED_GOODS','상품누락',2,'클레임 사유 중분류 - 상품누락','sungjae.hong','2017-06-18 20:11:50',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (65,37,'SOLD_OUT','품절',3,'클레임 사유 중분류 - 품절','sungjae.hong','2017-06-18 20:11:50',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (66,37,'PREPARE_GOODS_DELAY','상품준비지연',4,'클레임 사유 중분류 - 상품준비지연','sungjae.hong','2017-06-18 20:11:50',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (67,37,'CHANGE_GOODS','주문상품 정정',5,'클레임 사유 중분류 - 주문상품 정정','sungjae.hong','2017-06-18 20:11:50',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (68,38,'INEXPERIENCED','조작 미숙',1,'클레임 사유 중분류 - 조작 미숙','sungjae.hong','2017-06-18 20:22:57',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (69,38,'SYSTEM_ERROR','시스템 오류',2,'클레임 사유 중분류 - 시스템 오류','sungjae.hong','2017-06-18 20:22:57',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (70,38,'ETC','기타',3,'클레임 사유 중분류 - 기타','sungjae.hong','2017-06-18 20:22:57',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (71,NULL,'GROUP_TYPE','그룹 타입',1,'그룹 타입 parent','yjhan','2017-06-20 18:18:38',NULL,NULL);
INSERT INTO `codes` (`code_no`,`parent_code_no`,`code`,`code_name`,`display_order`,`description`,`creator`,`create_dt`,`updater`,`update_dt`) VALUES (72,71,'GENERAL','일반',1,'그룹 타입 - 일반','yjhan','2017-06-20 18:18:38',NULL,NULL);
